services:
  - type: web
    name: solarSysQuack
    env: node
    repo: https://github.com/pfknight8/SolarSysQuack.git
    buildCommand: npm install
    startCommand: npm start
    region: ohio
    plan: free
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase: 
          name: solar_system_quack
          property: connectionString

databases:
  - name: solar_system_quack
    plan: free
    databaseName: solar_system_quack