services:
  - type: web
    name: solarSytQuack
    env: node
    repo: https://github.com/pfknight8/SolarSysQuack.git
    buildCommand: npm install
    startCommand: npm start
    region: ohio
    plan: free
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase: 
          name: solarSystemQuack
          property: connectionString

databases:
  - name: solarSystemQuack
    plan: free
    databaseName: solarSystemQuack