'use strict';

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('planets', [
      {
        name: 'Mercury',
        overview:
          "The smallest planet in our solar system and nearest to the Sun, Mercury is only slightly larger than Earth's Moon. From the surface of Mercury, the Sun would appear more than three times as large as it does when viewed from Earth, and the sunlight would be as much as seven times brighter. Despite its proximity to the Sun, Mercury is not the hottest planet in our solar system that title belongs to nearby Venus, thanks to its dense atmosphere. Because of Mercury's elliptical egg-shaped orbit, and sluggish rotation, the Sun appears to rise briefly, set, and rise again from some parts of the planet's surface. The same thing happens in reverse at sunset.",
        mass: '3.285 x 10^23 kilograms',
        diameter: '4,880 kilometers (3,032 miles)',
        distance: '58 million kilometers (36 million miles)',
        factOne:
          "Mercury is the smallest planet in our solar system: With a diameter of only 4,880 km (3,032 miles), Mercury is just a little larger than Earth's moon. It is also the closest planet to the Sun and has the shortest orbital period of all the planets, completing one orbit in just 88 Earth days.",
        factTwo:
          "Mercury has a heavily cratered surface: Because it has no atmosphere to protect it from impacts, Mercury's surface is covered with impact craters. Some of these craters are hundreds of kilometers wide and date back to the early history of the solar system. Mercury's surface is also marked by long, steep cliffs (called scarps) that were likely formed by the planet's cooling and contracting interior.",
        factThree:
          "Mercury has a weak magnetic field: Despite its small size, Mercury has a magnetic field, which is about 1% as strong as Earth's. The origin of Mercury's magnetic field is still not well understood, but it is thought to be generated by the planet's partially molten iron core. The magnetic field is strong enough to deflect the solar wind, which is a stream of charged particles that flows from the Sun and can strip away a planet's atmosphere over time.",
        category: 'terrestrial',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Venus',
        overview:
          "Venus is the second planet from the Sun and is Earth's closest planetary neighbor. It's one of the four inner, terrestrial (or rocky) planets, and it's often called Earth's twin because it's similar in size and density. These are not identical twins, however there are radical differences between the two worlds.Venus has a thick, toxic atmosphere filled with carbon dioxide and it's perpetually shrouded in thick, yellowish clouds of sulfuric acid that trap heat, causing a runaway greenhouse effect. It's the hottest planet in our solar system, even though Mercury is closer to the Sun. Surface temperatures on Venus are about 900 degrees Fahrenheit (475 degrees Celsius) hot enough to melt lead.",
        mass: '4.87 x 10^24 kilograms',
        diameter: '12,104 kilometers (7,521 miles)',
        distance: '108 million kilometers (67 million miles)',
        factOne:
          "Venus is the hottest planet in our solar system: Despite not being the closest planet to the Sun, Venus has an average surface temperature of about 460 degrees Celsius (860 degrees Fahrenheit), which is hotter than the surface of Mercury, the planet closest to the Sun. The reason for Venus's extreme heat is its thick atmosphere, which traps heat from the Sun and creates a greenhouse effect.",
        factTwo:
          'Venus has a very slow rotation: Venus rotates very slowly on its axis, taking about 243 Earth days to complete one rotation. This means that a day on Venus is actually longer than a year on Venus, which takes about 225 Earth days to complete one orbit around the Sun. Additionally, Venus rotates in the opposite direction to most planets in our solar system, which means that the Sun rises in the west and sets in the east on Venus.',
        factThree:
          "Venus has no moons or rings: Unlike most of the other planets in our solar system, Venus does not have any moons or rings. This is thought to be because Venus's strong gravitational pull would make it difficult for any nearby objects to maintain a stable orbit around the planet. Additionally, Venus's thick atmosphere would make it difficult for any small moons or rings to form and survive.",
        category: 'terrestrial',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Earth',
        overview:
          "Our home planet is the third planet from the Sun, and the only place we know of so far that's inhabited by living things. While Earth is only the fifth largest planet in the solar system, it is the only world in our solar system with liquid water on the surface. Just slightly larger than nearby Venus, Earth is the biggest of the four planets closest to the Sun, all of which are made of rock and metal. The name Earth is at least 1,000 years old. All of the planets, except for Earth, were named after Greek and Roman gods and goddesses. However, the name Earth is a Germanic word, which simply means the ground.",
        mass: '5.97 x 10^24 kilograms',
        diameter: '12,742 km (7,918 miles)',
        distance: '149.6 million kilometers (93 million miles)',
        factOne:
          'Earth is the only planet known to support life: While there may be other planets in the universe that are capable of supporting life, as far as we know, Earth is the only one where life exists',
        factTwo:
          "Earth's atmosphere protects us from harmful radiation: The Earth's atmosphere is a thin layer of gases that surrounds the planet, extending up to about 10,000 km (6,200 miles) from the surface. This atmosphere plays a crucial role in protecting life on Earth by absorbing harmful ultraviolet radiation from the sun and regulating the planet's temperature.",
        factThree:
          'Earth is constantly changing: The Earth is a dynamic, ever-changing planet. It is shaped by natural processes such as plate tectonics, volcanic eruptions, erosion, and weathering. Over the course of its history, the Earth has undergone numerous transformations, including the formation of continents, the rise and fall of sea levels, and the evolution of life itself.',
        category: 'terrestrial',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Mars',
        overview:
          "Mars is the fourth planet from the Sun - a dusty, cold, desert world with a very thin atmosphere. Mars is also a dynamic planet with seasons, polar ice caps, canyons, extinct volcanoes, and evidence that it was even more active in the past. Mars is one of the most explored bodies in our solar system, and it's the only planet where we've sent rovers to roam the alien landscape. NASA currently has two rovers (Curiosity and Perseverance), one lander (InSight), and one helicopter (Ingenuity) exploring the surface of Mars.",
        mass: '6.39 x 10^23 kilograms',
        diameter: '6,779 kilometers (4,212 miles)',
        distance: '228 million kilometers (142 million miles)',
        factOne:
          'Mars has the largest volcano in our solar system: Olympus Mons is a shield volcano located on the Martian surface, and it is the largest volcano in the solar system. It stands at a height of 22 kilometers (14 miles), which is nearly three times the height of Mount Everest. Despite its size, Olympus Mons is thought to be extinct, with no evidence of recent volcanic activity.',
        factTwo:
          "Mars has a very thin atmosphere: The Martian atmosphere is about 100 times thinner than Earth's atmosphere, and it is mostly composed of carbon dioxide. The thin atmosphere means that Mars has a very weak greenhouse effect, which results in a cold and dry climate. However, the Martian atmosphere is thick enough to cause dust storms that can cover the entire planet for weeks or even months.",
        factThree:
          'Mars has evidence of past liquid water on its surface: While Mars is currently a cold and dry planet, there is evidence that liquid water existed on its surface in the past. Images taken by spacecraft have revealed features on the Martian surface, such as dry riverbeds and minerals that can only form in the presence of liquid water. Scientists believe that Mars may have had a warm and wet climate in its early history, but it eventually lost most of its atmosphere and surface water.',
        category: 'terrestrial',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Jupiter',
        overview:
          "Jupiter has a long history of surprising scientists - all the way back to 1610 when Galileo Galilei found the first moons beyond Earth. That discovery changed the way we see the universe. Fifth in line from the Sun, Jupiter is, by far, the largest planet in the solar system - more than twice as massive as all the other planets combined Jupiter's familiar stripes and swirls are actually cold, windy clouds of ammonia and water, floating in an atmosphere of hydrogen and helium. Jupiter's iconic Great Red Spot is a giant storm bigger than Earth that has raged for hundreds of years. One spacecraft - NASA's Juno orbiter - is currently exploring this giant world.",
        mass: '1.898 x 10^27 kilograms',
        diameter: '139,822 kilometers (86,881 miles)',
        distance: '778 million kilometers (483 million miles)',
        factOne:
          "Jupiter has a strong magnetic field: Jupiter has the strongest magnetic field of any planet in our solar system, with a magnetic field strength about 20,000 times stronger than Earth's. This magnetic field creates intense radiation belts around Jupiter, which can be hazardous for spacecraft and can cause auroras to occur on the planet.",
        factTwo:
          'Jupiter has a very short day: Despite its large size, Jupiter rotates very quickly, completing one full rotation on its axis in just under 10 hours. This rapid rotation causes Jupiter to be noticeably flattened at the poles and bulging at the equator.',
        factThree:
          'Jupiter has at least 79 known moons: Jupiter has the largest number of moons of any planet in our solar system. The four largest moons, known as the Galilean moons, are named Io, Europa, Ganymede, and Callisto. These moons are some of the largest objects in the solar system outside of the sun and the eight planets.',
        category: 'gas giant',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Saturn',
        overview:
          "Saturn is the sixth planet from the Sun and the second-largest planet in our solar system. Adorned with thousands of beautiful ringlets, Saturn is unique among the planets. It is not the only planet to have rings - made of chunks of ice and rock - but none are as spectacular or as complicated as Saturn's. Like fellow gas giant Jupiter, Saturn is a massive ball made mostly of hydrogen and helium.",
        mass: '5.68 x 10^26 kilograms',
        diameter: '116,460 kilometers (72,365 miles)',
        distance: '1.4 billion kilometers (870 million miles)',
        factOne:
          'Saturn has the most extensive and complex ring system of any planet in the solar system. The rings are made up of countless small particles of ice and rock, and they range in size from tiny specks to large boulders. Some of the gaps in the rings are created by small moons that orbit within them.',
        factTwo:
          'Saturn is the least dense planet in the solar system. Its average density is less than that of water, which means that if there were a large enough body of water, Saturn would float on it.',
        factThree:
          "Saturn has a unique hexagonal-shaped cloud pattern at its north pole. The hexagon is approximately 25,000 kilometers in diameter and rotates with the planet. Its exact cause is still unknown, but scientists think it may be related to the planet's fast rotation and the jet stream in its atmosphere.",
        category: 'gas giant',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Uranus',
        overview:
          "Uranus is the seventh planet from the Sun, and has the third-largest diameter in our solar system. It was the first planet found with the aid of a telescope, Uranus was discovered in 1781 by astronomer William Herschel, although he originally thought it was either a comet or a star. It was two years later that the object was universally accepted as a new planet, in part because of observations by astronomer Johann Elert Bode. Herschel tried unsuccessfully to name his discovery Georgium Sidus after King George III. Instead, the scientific community accepted Bode's suggestion to name it Uranus, the Greek god of the sky, as suggested by Bode.",
        mass: '8.68 x 10^25 kilograms',
        diameter: '50,724 kilometers (31,518 miles)',
        distance: '2.87 billion kilometers (1.78 billion miles)',
        factOne:
          'Uranus is the seventh planet from the Sun and is classified as an ice giant, along with Neptune.',
        factTwo:
          'Uranus is unique in our solar system for its tilted axis of rotation, which is tilted at an angle of 97.77 degrees relative to its orbit around the Sun. This means that its poles are almost in the plane of its orbit, and it rotates on its side as it orbits the Sun.',
        factThree:
          'Uranus has a very thin set of rings surrounding it, which were first discovered in 1977 by astronomers James L. Elliot, Edward W. Dunham, and Jessica Mink.',
        category: 'ice planet',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Neptune',
        overview:
          "Dark, cold, and whipped by supersonic winds, ice giant Neptune is the eighth and most distant planet in our solar system. More than 30 times as far from the Sun as Earth, Neptune is the only planet in our solar system not visible to the naked eye and the first predicted by mathematics before its discovery. In 2011 Neptune completed its first 165-year orbit since its discovery in 1846. NASA's Voyager 2 is the only spacecraft to have visited Neptune up close. It flew past in 1989 on its way out of the solar system.",
        mass: '1.02 x 10^26 kilograms',
        diameter: '49,244 kilometers (30,600 miles)',
        distance: '4.5 billion kilometers (2.8 billion miles)',
        factOne:
          'Neptune is the fourth-largest planet by diameter and the third-largest by mass in our solar system.',
        factTwo:
          'It has the strongest sustained winds of any planet in the solar system, with wind speeds reaching up to 2,100 km/hour (1,300 mph).',
        factThree:
          'Neptune has a system of rings, although they are faint and hard to see from Earth.',
        category: 'ice planet',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Pluto',
        overview:
          "Pluto is a dwarf planet in the Kuiper Belt, a donut-shaped region of icy bodies beyond the orbit of Neptune. There may be millions of these icy objects, collectively referred to as Kuiper Belt objects (KBOs) or trans-Neptunian objects (TNOs), in this distant region of our solar system. Pluto - which is smaller than Earth's Moon - has a heart-shaped glacier that's the size of Texas and Oklahoma. This fascinating world has blue skies, spinning moons, mountains as high as the Rockies, and it snows - but the snow is red.",
        mass: '1.31 x 10^22 kilograms',
        diameter: '2,377 kilometers (1477 miles)',
        distance: '5.9 billion kilometers (3.67 billion miles)',
        factOne:
          'Pluto has a highly eccentric and inclined orbit that takes it closer to the sun than Neptune for a portion of its orbit.',
        factTwo:
          "Pluto is smaller than many moons in our solar system. It has a diameter of just 2,377 kilometers, which is smaller than the Earth's moon and several other moons in the solar system.",
        factThree:
          'Pluto has a heart-shaped feature on its surface, which is named "Tombaugh Regio" after Pluto\'s discoverer, Clyde Tombaugh. The feature is about 1,600 kilometers wide and is thought to be relatively young geologically speaking, possibly formed by a collision with a large object.',
        category: 'dwarf planet',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // {
      //   name: 'Ceres',
      //   overview: "Ceres is a dwarf planet in the asteroid belt between the orbits of Mars and Jupiter. Ceres was the first object to be discovered in the asteroid belt, when Giuseppe Piazzi spotted it in 1801.",
      //   mass: '1.31 x 10^22 kilograms',
      //   diameter: '939 kilometers (584 miles)',
      //   distance: '413 million kilometers (257 million miles)',
      //   factOne: 'Ceres is the largest object in the asteroid belt.',
      //   factTwo:
      //     'Ceres accounts for about 40% of the mass of the asteroid belt.',
      //   factThree:
      //     'Ceres is the only dwarf planet located in the inner solar system. Ceres meets two of the three rules that would allow it to be planet in its own right (which would make it the fifth from the Sun): it is massive enough to have achieved hydrostatic equilibrium (nearly round shape), and it is not a star or satellite of another object. It has failed to clear its own orbit, residing in the region known as the asteroid belt, thus keeping it a dwarf planet.',
      //   category: 'dwarf planet',
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
    ]);
  },

  async down(queryInterface, Sequelize) {
    return queryInterface.bulkDelete('planets');
  },
};
