'use strict';

module.exports = {
  async up(queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
     */
    await queryInterface.bulkInsert('moons', [
      {
        name: "Earth's Moon",
        mass: '7.34 x 10^22 kilograms (81 billion tons)',
        diameter: '3,476 kilometers (2,159 miles)',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'it is in synchronous rotation with Earth, meaning that it takes the same amount of time to rotate once on its axis as it does to complete one orbit around Earth. This is why we always see the same side of the moon facing Earth.',
        planet_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Phobos',
        mass: '1.08 × 10^16 kilograms (11 billion tons)',
        diameter: '22 kilometers (14 miles)',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Phobos is one of the least reflective objects in the Solar System, with a surface that is about as dark as coal. ',
        planet_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Deimos',
        mass: '11.8 x 10^15 kilograms (2 billion tons)',
        diameter: '12 kilometers (7.5 miles)',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          "Deimos has an irregular shape and a heavily cratered surface, suggesting that it is a captured asteroid rather than a moon that formed from Mars' accretion disk.",
        planet_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Ganymede',
        mass: '1.4819 x 10^23 kilograms',
        diameter: '5,262 kilometers (3,273 miles)',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history: '',
        planet_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Callisto',
        mass: '1.0759 x 10^23 kilograms',
        diameter: '4,821 kilometers (2,995 miles)',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Callisto is the second-largest moon of Jupiter. It has the most heavily cratered surface of any moon in the solar system, and is thought to have a subsurface ocean of liquid water.',
        planet_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Io',
        mass: '8.9319 x 10^22 kilograms',
        diameter: '3,643 kilometers (2,263 miles)',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Io is the most volcanically active object in the solar system. Its surface is covered in hundreds of active volcanoes, many of which spew out sulfur dioxide and other gases.',
        planet_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Europa',
        mass: '4.7998 x 10^22 kilograms',
        diameter: '3,122 kilometers (1,940 miles)',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Europa is one of the most intriguing moons in the solar system. Its surface is covered in a layer of ice that is thought to conceal a subsurface ocean of liquid water, which could potentially support life.',
        planet_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Amalthea',
        mass: '2.08 x 10^18 kilograms',
        diameter: '250 kilometers (155 miles)',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Amalthea is one of the smaller moons of Jupiter. It is irregularly shaped and has a reddish color, and is thought to be made up primarily of rock.',
        planet_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Himalia',
        mass: '4.01 x 10^18 kilograms',
        diameter: '170 kilometers (106 miles)',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          "Himalia is one of the largest of Jupiter's irregularly shaped moons. It is thought to be made up primarily of rock and may be a captured asteroid.",
        planet_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Thebe',
        mass: '4.3 x 10^17 kilograms',
        diameter: '100 kilometers (62 miles)',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Thebe is a small, irregularly shaped moon of Jupiter. Its surface is heavily cratered, and it is thought to be made up primarily of rock.',
        planet_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Elara',
        mass: '8.7 x 10^17 kilograms',
        diameter: '86 kilometers (53 miles)',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          "Elara is another of Jupiter's irregularly shaped moons. It is thought to be made up primarily of rock and may be a captured asteroid.",
        planet_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Pasiphae',
        mass: '2.3 x 10^18 kilograms',
        diameter: '60 kilometers (37 miles)',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Pasiphae is a small, irregularly shaped moon of Jupiter. It is thought to be made up primarily of rock and may be a captured asteroid.',
        planet_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Sinope',
        mass: '2.9 x 10^18 kilograms',
        diameter: '38 kilometers (24 miles)',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          "Sinope is one of Jupiter's smallest known moons. It is thought to be made up primarily of rock and may be a captured asteroid.",
        planet_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Titan',
        mass: '1.35 x 10^23 kilograms',
        diameter: '5,150 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Titan is the only moon in the solar system with a dense atmosphere, and it is the second-largest moon in the solar system.',
        planet_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Rhea',
        mass: '2.31 x 10^21 kilograms',
        diameter: '1528 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Rhea has a heavily cratered surface and a few large fractures on its icy surface.',
        planet_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Iapetus',
        mass: '1.81 x 10^21 kilograms',
        diameter: '1470 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Iapetus has a distinctive two-tone appearance, with one half of the moon being much darker than the other.',
        planet_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Dione',
        mass: '6.17 x 10^20 kilograms',
        diameter: '1062 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Tethys has a large impact crater called Odysseus that is over 400 km in diameter.',
        planet_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Enceladus',
        mass: '1.08 x 10^20 kilograms',
        diameter: '504 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Enceladus is known for its active geysers, which spew water vapor and icy particles into space.',
        planet_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Mimas',
        mass: '3.75 x 10^19 kilograms',
        diameter: '396 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Mimas has a large impact crater called Herschel that is over 130 km in diameter, and it gives the moon a resemblance to the "Death Star" from Star Wars.',
        planet_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Hyperion',
        mass: '5.62 x 10^18 kilograms',
        diameter: '270 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Hyperion has a highly irregular shape and a sponge-like appearance due to its porous, icy composition.',
        planet_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Phoebe',
        mass: '8.29 x 10^18 kilograms',
        diameter: '213 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Phoebe is one of the outermost moons of Saturn and is thought to be a captured object from the Kuiper Belt, a region of icy bodies beyond Neptune.',
        planet_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Janus',
        mass: '1.90 x 10^18 kilograms',
        diameter: '179 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Janus and its partner moon Epimetheus share the same orbit around Saturn and occasionally swap places due to their gravitational interaction.',
        planet_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Epimetheus',
        mass: '5.27 x 10^17 kilograms',
        diameter: '153 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Epimetheus and Janus are thought to be remnants of a larger moon that broke apart.',
        planet_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Titania',
        mass: '3.5 x 10^21 kilograms',
        diameter: '1,578 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Titania has a heavily cratered surface, as well as valleys and canyons that suggest some form of tectonic activity.',
        planet_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Oberon',
        mass: '3.0 x 10^21 kilograms',
        diameter: '1523 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Oberon has a heavily cratered surface, as well as a large canyon system known as Mommur Chasma.',
        planet_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Umbriel',
        mass: '1.2 x 10^21 kilograms',
        diameter: '1169 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Umbriel has a heavily cratered surface, as well as a large, dark basin known as Wunda Crater.',
        planet_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Ariel',
        mass: '1.3 x 10^21 kilograms',
        diameter: '1158 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Ariel has a varied surface, with extensive fault systems, valleys, and canyons, as well as a large, smooth region known as the Ariel Planitia.',
        planet_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Miranda',
        mass: '6.4 x 10^19 kilograms',
        diameter: '471 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Miranda has a highly varied surface, with cliffs, canyons, and bizarre-looking features known as coronae, which are thought to be the result of tectonic activity.',
        planet_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Puck',
        mass: '2.9 x 10^1 kilograms',
        diameter: '162 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          "Puck has a heavily cratered surface and is one of the smallest of Uranus's known moons.",
        planet_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Portia',
        mass: '1.3 x 10^17 kilograms',
        diameter: '135 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Portia has a relatively smooth surface and is named after a character from Shakespeare\'s play "The Merchant of Venice."',
        planet_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Juliet',
        mass: '7.6 x 10^16 kilograms',
        diameter: '94 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          "Juliet is one of the smaller of Uranus's known moons and has a heavily cratered surface.",
        planet_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Cressida',
        mass: '3.3 x 10^16 kilograms',
        diameter: '80 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Cressida has a heavily cratered surface and is named after a character from Shakespeare\'s play "Troilus and Cressida."',
        planet_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Belinda',
        mass: '1.2 x 10^16 kilograms',
        diameter: '68 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Belinda has a heavily cratered surface and is named after a character from Alexander Pope\'s poem "The Rape of the Lock."',
        planet_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Triton',
        mass: '2.14 x 10^22 kilograms',
        diameter: '2707 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          "Triton is the only large moon in the solar system that orbits in the opposite direction of its planet's rotation.",
        planet_id: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Nereid',
        mass: '3.1 x 10^19 kilograms',
        diameter: '340 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Nereid has one of the most eccentric orbits of any moon in the solar system.',
        planet_id: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Proteus',
        mass: '5.2 x 10^19 kilograms',
        diameter: '420 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Proteus is the largest irregularly shaped moon in the solar system.',
        planet_id: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Larissa',
        mass: '4.2 x 10^17 kilograms',
        diameter: '194 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Larissa is named after a lover of Poseidon, the Greek god of the sea.',
        planet_id: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Despina',
        mass: '2.1 x 10^17 kilograms',
        diameter: '150 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history: 'Despina was discovered by the Voyager 2 spacecraft in 1989.',
        planet_id: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Galatea',
        mass: ' 2.1 x 10^17 kilograms',
        diameter: '158 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Galatea is named after one of the sea nymphs in Greek mythology.',
        planet_id: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Thalassa',
        mass: '7.5 x 10^16 kilograms',
        diameter: '82 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Thalassa is named after the Greek goddess of the sea, and is also one of the seven inner moons of Neptune.',
        planet_id: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Naiad',
        mass: '1.9 x 10^16 kilograms',
        diameter: '58 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Naiad is one of the smallest moons in the solar system, and was discovered by Voyager 2 in 1989.',
        planet_id: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Sao',
        mass: '5.7 x 10^15 kilograms',
        diameter: '44 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Sao is named after a mythological Amazon warrior, and was discovered by Voyager 2 in 1989.',
        planet_id: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Laomedeia',
        mass: '4.1 x 10^15 kilograms',
        diameter: '42 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Laomedeia is named after one of the 50 daughters of King Thespius in Greek mythology.',
        planet_id: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Charon',
        mass: '1.52 x 10^21 kilograms',
        diameter: '1212 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Charon is the largest moon of Pluto and is so big that some scientists consider the Pluto-Charon system to be a "double dwarf planet". Charon is covered in water ice, and has a large canyon called Serenity Chasma that is over 1,000 kilometers long.',
        planet_id: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Styx',
        mass: 'unknown',
        diameter: '7-21 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Styx is the second-largest moon of Pluto, and is named after the river Styx in Greek mythology. It was discovered in 2012 by astronomers using the Hubble Space Telescope.',
        planet_id: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Nix',
        mass: 'unknown',
        diameter: '20-50 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          'Nix is the third-largest moon of Pluto, and was also discovered in 2005 by the same team that discovered Hydra. It has a reddish color and an irregular shape.',
        planet_id: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Kerberos',
        mass: 'unknown',
        diameter: '12-34 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          "Kerberos is the smallest of Pluto's five moons, and was discovered in 2011 using the Hubble Space Telescope. It has a highly reflective surface, which suggests it is covered in water ice.",
        planet_id: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Hydra',
        mass: 'known',
        diameter: '30-40 kilometers',
        // distance: 1,
        // ap_distance: 1,
        // peri_distance: 1,
        history:
          "Hydra is the second-largest of Pluto's moons and was discovered in 2005 by a team of astronomers using the Hubble Space Telescope. It has a irregular shape and is thought to be covered in water ice.",
        planet_id: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    return queryInterface.bulkDelete('moons');
  },
};
